name: "Tracking services detection action"
description: "Detect the tracking service on a website"

inputs:
  url:
    description: URL to read
    required: true
  output:
    description: Path to output file
    default: scans/tracking.json
    required: false

runs:
  using: "composite"
  steps:
    - name: Get URL HTML
      uses: SocialGouv/dashlord-actions/get-html@v1
      with:
        url: ${{ inputs.url }}
        output: tracking-html.html
    - shell: bash
      run: |
        set +e

        if grep -Eq "(eulerian)" ./tracking-html.html; then
          JSON="{\"tracking\": true, \"service\": \"eulerian\"}"
        elif grep -Eq "(matomo)" ./tracking-html.html; then
          JSON="{\"tracking\": true, \"service\": \"matomo\"}"
        elif grep -Eq "(piwik)" ./tracking-html.html; then
          JSON="{\"tracking\": true, \"service\": \"piwik\"}"
        elif grep -Eq "(piano|aticdn|smarttag)" ./tracking-html.html; then
          JSON="{\"tracking\": true, \"service\": \"piano\"}"
        elif grep -Eq "(google|gtag|gtm)" ./tracking-html.html; then
          JSON="{\"tracking\": true, \"service\": \"google\"}"
        fi

        echo "$JSON" > ${{ github.workspace }}/${{ inputs.output }}
